### ISSUE TITLE
Error: invalid output file

### ISSUE THREAD

**Issue by DarylWM** [mhoopmann/hardklor#6]
Hello,

I get the error message below. Looking at the source didn't tell me why it's failing (not quite sure what that part of the code is doing). I'm running Hardklor 2.3 on Ubuntu 16.04. Can you tell me how to avoid the error?

daryl@ubuntu:~/random-features$ ../hardklor/hardklor Hardklor.conf
Hardklor v2.3.0, August 14 2015
Mike Hoopmann, Mike MacCoss
Copyright 2007-2015
University of Washington
Invalid output file.

My Hardklor.conf:

[Hardklor.conf.txt](https://github.com/mhoopmann/hardklor/files/1937921/Hardklor.conf.txt)

Thanks.

**Comment by mhoopmann** [comment]
Hi Daryl,
Could you try performing a dos2unix on that file and then run it again?

If that is indeed the problem, I'll see if I can find a more elegant workaround inside Hardklor.

Cheers,
Mike

**Comment by DarylWM** [comment]
That was it - thanks Mike.
